name: Terraform Destroy

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.6.6'  # Use your desired version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Add Debugging
      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
