name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Confirm you want to destroy resources'
        required: true
        default: 'false'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Destroy only if the user confirms
      - name: Terraform Destroy
        if: ${{ github.event.inputs.confirm_destroy == 'true' }}
        run: terraform destroy -auto-approve
